services:
  backend:
    build: ./server
    ports:
      - "5555:5555"
    env_file:
      - ./server/.env
  
  frontend:
    build:
      context: ./client
      args:
        VITE_BASE_URL: "http://localhost:5555/"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BASE_URL=http://localhost:5555/
    networks:
      - ecohub-network
  
  cypress:
    image: cypress/included:latest
    container_name: cypress
    networks:
      - ecohub-network
    volumes:
      - ./client/cypress/e2e:/e2e
    working_dir: /e2e
    entrypoint: ["npx", "cypress", "run"]
    depends_on:
      - frontend

networks:
  ecohub-network:
    driver: bridge