services:
  backend:
    build: ./server
    ports:
      - "5555:5555"
    environment:
      - DB_URL = ${DB_URL}
      - PORT = ${PORT}
  
  frontend:
    build:
      context: ./client
      args:
        VITE_BASE_URL: "http://localhost:5555/"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BASE_URL=http://localhost:5555/