name: Personal Diary

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-jenkinsfile:
    name: Run Jenkins File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Jenkinsfile
        uses: jenkinsci/jenkinsfile-runner-action@v1
        with:
          jenkinsfile: 'Jenkinsfile'
          pluginstxt: plugins.txt
        env:
          DB_URL: ${{secrets.DATABASE_URL}}
          PORT: ${{secrets.PORT}}
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}