name: Personal Diary

on:
  pull_request:
    branches:
      - master

jobs:
  server-test:
    name: Ecohub Server Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:  ./server
    
    strategy:
      matrix:
        node-version: [21.7.3]
    
    environment: prod
    
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v21.7.3
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm ci
      
      - name: Test API endpoints
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          PORT: ${{secrets.PORT}}
        run: npm test
